/* 
 * Sign up for a key at this location: 
 * http://code.google.com/apis/maps/signup.html
 * place the in this file
 * the forcekey should specify *.force.com as the domain for any visualforce pages
 * the key should specify *.salesforce.com for geocode requests that start on the server
 */

public class geoApiKey {
	// *.salesforce.com 
    public static string key = 'ABQIAAAACfpTt5vg3R9sMCkWTm9m2hQRmoUgOUS0AdglA8vMXXHrIXZp6RTPWGCB4y2z2sS345sKKguLkpqUaA';
    
    // *.force.com
    public static string forcekey = 'ABQIAAAACfpTt5vg3R9sMCkWTm9m2hQLNlfCSZsNWrNrjOuv5jQjg1XmWxQVXvSsa3_sWXPtkKTYKOfC30unmg';
 
}