global class QualityMonitor {
    
    public void runTests(String namespace) {
        //if namespace is not specified, run all tests
        
    }
    
    public void logTestResult(ApexTestResult result) {
    
    }
    /*
    public void logCodeCoverage(ApexCodeCoverage coverage) {
    
    }
    
    public void logCodeCoverageAggregate(ApexCodeCoverageAggregate coverageAgg) {
    
    }
    */
    
}